name: Bump AUR version

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up AUR keys
        run: |
          # Write deploy key to ~/.ssh/id_ed25519. Git will automatically
          # use ~/.ssh/id_ed25519 to log in to github.com (see `man ssh`)
          mkdir -p ~/.ssh
          echo "${{ secrets.AUR_DEPLOY_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          echo "aur.archlinux.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEuBKrPzbawxA/k2g6NcyV5jmqwJ2s+zpgZGZ7tpLIcN
          aur.archlinux.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKF9vAFWdgm9Bi8uc+tYRBmXASBb5cB5iZsB7LOWWFeBrLp3r14w0/9S2vozjgqY5sJLDPONWoTTaVTbhe3vwO8CBKZTEt1AcWxuXNlRnk9FliR1/eNB9uz/7y1R0+c1Md+P98AJJSJWKN12nqIDIhjl2S1vOUvm7FNY43fU2knIhEbHybhwWeg+0wxpKwcAd/JeL5i92Uv03MYftOToUijd1pqyVFdJvQFhqD4v3M157jxS5FTOBrccAEjT+zYmFyD8WvKUa9vUclRddNllmBJdy4NyLB8SvVZULUPrP3QOlmzemeKracTlVOUG1wsDbxknF1BwSCU7CmU6UFP90kpWIyz66bP0bl67QAvlIc52Yix7pKJPbw85+zykvnfl2mdROsaT8p8R9nwCdFsBc9IiD0NhPEHcyHRwB8fokXTajk2QnGhL+zP5KnkmXnyQYOCUYo3EKMXIlVOVbPDgRYYT/XqvBuzq5S9rrU70KoI/S5lDnFfx/+lPLdtcnnEPk=
          aur.archlinux.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLMiLrP8pVi5BFX2i3vepSUnpedeiewE5XptnUnau+ZoeUOPkpoCgZZuYfpaIQfhhJJI5qgnjJmr4hyJbe/zxow=" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_ed25519
      - name: Clone and edit AUR repo
        run: |
          sha=$(curl -s "https://codeload.github.com/n0n1m/aiomax/tar.gz/refs/tags/${{ github.event.release.tag_name }}" | sha256sum - | cut -d " " -f1)
          git clone ssh://aur@aur.archlinux.org/python-aiomax-autotest.git aur-repo
          cd aur-repo
          sed -i 's/^pkgver=.*/pkgver=${{ github.event.release.tag_name }}/' PKGBUILD
          sed -i 's/^pkgrel=.*/pkgrel=1/' PKGBUILD
          sed -i "s/^sha256sums=.*/sha256sums=('$sha')/" PKGBUILD
          sed -i 's/pkgver = .*/pkgver = ${{ github.event.release.tag_name }}/' .SRCINFO
          sed -i 's/pkgrel = .*/pkgrel = 1/' .SRCINFO
          sed -i "s/sha256sums = .*/sha256sums = $sha/" .SRCINFO
          sed -i 's/\/tar.gz\/refs\/tags\/.*/\/tar.gz\/refs\/tags\/${{ github.event.release.tag_name }}/' .SRCINFO
      - name: Push changes to AUR
        run: |
          cd ${{ github.workspace }}/aur-repo
          git config user.name "autobump"
          git config user.email "no@thankyou.com"
          git add PKGBUILD .SRCINFO
          git commit -m "bump version to ${{ github.event.release.tag_name }}"
          git push